// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRoGNQl-0ij0Lahy6xLh-sgBMLtK7iTk',
    appId: '1:700741537981:web:a7ec68a7b8cf85da6427d4',
    messagingSenderId: '700741537981',
    projectId: 'wastefood-dfcf5',
    authDomain: 'wastefood-dfcf5.firebaseapp.com',
    storageBucket: 'wastefood-dfcf5.firebasestorage.app',
    measurementId: 'G-ERQ15M3DPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFSh41my5u5C6fFTaXgf83xR4pQ0ASyY',
    appId: '1:700741537981:android:b4fe5f6042634a0f6427d4',
    messagingSenderId: '700741537981',
    projectId: 'wastefood-dfcf5',
    storageBucket: 'wastefood-dfcf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikO_DHVFN2lgPfybYGWT5odGqs-pL9Ts',
    appId: '1:700741537981:ios:837aa6164e31cacb6427d4',
    messagingSenderId: '700741537981',
    projectId: 'wastefood-dfcf5',
    storageBucket: 'wastefood-dfcf5.firebasestorage.app',
    iosClientId: '700741537981-cinu8ut2ibe0e0g2o39du7r09sh4eim9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastefood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikO_DHVFN2lgPfybYGWT5odGqs-pL9Ts',
    appId: '1:700741537981:ios:837aa6164e31cacb6427d4',
    messagingSenderId: '700741537981',
    projectId: 'wastefood-dfcf5',
    storageBucket: 'wastefood-dfcf5.firebasestorage.app',
    iosClientId: '700741537981-cinu8ut2ibe0e0g2o39du7r09sh4eim9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastefood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMRoGNQl-0ij0Lahy6xLh-sgBMLtK7iTk',
    appId: '1:700741537981:web:bc0df019b39c3bef6427d4',
    messagingSenderId: '700741537981',
    projectId: 'wastefood-dfcf5',
    authDomain: 'wastefood-dfcf5.firebaseapp.com',
    storageBucket: 'wastefood-dfcf5.firebasestorage.app',
    measurementId: 'G-5TJTTP5EE9',
  );
}
